version: '3.8'
services:
#  bs-userinfo:
#    container_name: 'bs-userinfo'
#    image: 'social-medium/bs-userinfo'
#    build: ./
#    ports:
#      - '8581:8581'
#    depends_on:
#      - userinfo_db
#    command: mvn clean spring-boot:run
#    # Pass environment variables to the service
#    environment:
#      # The inside port will be used by the dependent services
#      SPRING_DATASOURCE_HOST: userinfo_db
#      SPRING_DATASOURCE_DB: userinfo
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: secret
#      SPRING_DATASOURCE_DB_PORT: 5432
#      SERVER_PORT: 8581
#      ACTIVE_PROFILE: dev
#    networks:
#      - social_medium
#    volumes:
#      - type: volume
#        source: vol_userinfo
#        target: "/home/mainul35/Documents/userinfo/static/resources"
  userinfo_test_db:
    image: 'postgres'
    container_name: 'userinfo_test_container'
    volumes:
      - type: volume
        source: vol_userinfo_test
        target: "/home/mainul35/Documents/userinfo_test_db_data"
    ports:
      - '6433:5432'
    environment:
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=userinfo_test'
    networks:
      - social_medium_test_network
#    extra_hosts:
#      - 'social_medium_network:192.168.1.100'
  rabbitmq_test:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_test
    environment:
      RABBITMQ_DEFAULT_USER: social_community_user
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - '6672:5672'
      - '25672:15672'
    networks:
      - social_medium_test_network
volumes:
  vol_userinfo_test:
networks:
  social_medium_test_network:
    name: social_medium_test_network
    driver: bridge